version: '3.4'

services:
  db:
    image: "edinat/db:130152"
    ports:
      - "1433:1433"
  restoran:
    image: ${DOCKER_REGISTRY-}restoran
    build:
      context: .
      dockerfile: Restoran/Dockerfile
    depends_on:
             - db
    